src/main/java/com/filar/patman/data/entities/Member.java
package com.filar.patman.data.entities;

import com.filar.patman.data.entities.task.Task;
import com.filar.patman.data.helpers.Authority;
import com.filar.patman.data.helpers.TaskStatus;
import org.apache.commons.lang3.builder.HashCodeBuilder;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Created by kamil on 23.02.16.
 */
@Entity
public class Member {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;
	@NotNull
	@Size(min=2, max=50, message = "First name must be between 2 and 50 characters long")
	private String firstName;
	@NotNull
	@Size(min=2, max=50, message = "Surname must be between 2 and 50 characters long")
	private String surname;
	@NotNull
	@Size(min=4, max=200, message = "Password must be at least 4 characters long")
	private String password;
	@NotNull
	@Column(unique = true)
	private String email;
	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(
			name = "Member_Task",
			joinColumns = @JoinColumn(name = "Member_Id", referencedColumnName = "id"),
			inverseJoinColumns = @JoinColumn(name = "Task_Id", referencedColumnName = "id")
	)
	private Set<Task> assignedTasks = new HashSet<>();
	@ManyToMany(fetch=FetchType.EAGER, mappedBy = "managers")
	private Set<Project> managedProjects = new HashSet<>();
	@ElementCollection(fetch = FetchType.EAGER)
	@Enumerated
	private Set<Authority> authorities = new HashSet<>();

	public Member() {
		super();
	}

	public Member(Long id, String firstName, String surname, String password, String email,
				  Set<Task> assignedTasks, Set<Project> managedProjects, Set<Authority> authorities) {
		this(id, firstName, surname, password, email);
		this.assignedTasks = assignedTasks;
		this.managedProjects = managedProjects;
		this.authorities = authorities;
	}
	public Member(Long id, String firstName, String surname, String password, String email){
		this.id = id;
		this.firstName = firstName;
		this.surname = surname;
		this.password = password;
		this.email = email;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<Task> getAssignedTasks() {
		return assignedTasks;
	}

	public void setAssignedTasks(Set<Task> assignedTasks) {
		this.assignedTasks = assignedTasks;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set<Project> getManagedProjects() {
		return managedProjects;
	}

	public void setManagedProjects(Set<Project> managedProjects) {
		this.managedProjects = managedProjects;
	}

	public Set<Authority> getAuthorities() {
		return authorities;
	}

	public void setAuthorities(Set<Authority> authorities) {
		this.authorities = authorities;
	}

	public void addManagedProject(Project project){
		managedProjects.add(project);
	}

	public void deleteManagedProject(Project project){
		managedProjects.remove(project);
	}

	public String getFullName(){ return firstName +" "+ surname; }

	public void assignTask(Task task) {
		assignedTasks.add(task);
	}

	public void removeTask(Task task) {
		assignedTasks.remove(task);
	}


	// get assigned tasks that have the specified status
	public Set<Task> getTasksWithStatus(TaskStatus status) {
		return new HashSet<Task>(
				assignedTasks.stream().filter(
						(i)->i.getStatus()==status
				).collect( Collectors.toList() )
		);
	}

	public int getNumberOfActiveTasks(){
		return getTasksWithStatus(TaskStatus.IN_PROGRESS).size()+getTasksWithStatus(TaskStatus.NEW).size();
	}



	@Override
	public int hashCode() {
		return new HashCodeBuilder().append(email).toHashCode();
	}

	@Override
	public boolean equals(Object m) {
		if(m.getClass()!=this.getClass()) return false;
		if ( ((Member)m ).getEmail().equals(email) ) return true;
		return false;
	}
}

src/main/java/com/filar/patman/web/MemberController.java
package com.filar.patman.web;

import com.filar.patman.data.entities.Member;
import com.filar.patman.data.helpers.Authority;
import com.filar.patman.data.service.MemberRepository;
import com.filar.patman.web.helpers.Helpers;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.Errors;
import org.springframework.web.bind.annotation.*;

import javax.validation.Valid;

/**
 * Created by kamil on 29.02.16.
 */
@Controller
@RequestMapping("/member")
public class MemberController {
	@Autowired
	MemberRepository memberRepository;
	@Autowired
	PasswordEncoder passwordEncoder;

	@RequestMapping(value = "/register", method = RequestMethod.GET)
	public String register(Model model){

		model.addAttribute("newMember", new Member());
		model.addAttribute("passwordsMatch", true);
		return "member/register";
	}

	@RequestMapping(value = "/register", method = RequestMethod.POST)
	public String postRegister(@RequestParam("retypedPassword") String retypedPassword,
							   @Valid @ModelAttribute("newMember") Member newMember, Errors errors, Model model
	){

		if (!newMember.getPassword().equals(retypedPassword)){
			model.addAttribute("passwordsMatch", false);
			return "member/register";

		} else {
			if (errors.hasErrors()){
				model.addAttribute("passwordsMatch", true);
				return "member/register";
			} else {
				newMember.setPassword(passwordEncoder.encode(newMember.getPassword()));
				newMember.setEmail(newMember.getEmail().toLowerCase());
				// first user is an admin
				if(memberRepository.count()==0) newMember.getAuthorities().add(Authority.ADMIN);
				// e-mail must be unique, if it's not, save() will throw an exception, then the message is added to errors
				try{
					memberRepository.save(newMember);
				}catch(DataIntegrityViolationException e){
					errors.reject("org.springframework.dao.DataIntegrityViolationException","Member with entered e-mail already exists.");
					return "member/register";
				}
				return "redirect:show/" + newMember.getId() ;
			}
		}
	}

	@RequestMapping(value = "/show/{id}", method = RequestMethod.GET)
	public String showMember(Model model, @PathVariable Long id){
		Member member = memberRepository.findOne(id);
		if(member == null) return Helpers.notFoundRedirect(id, "member");

		Helpers.fillModelWithMembersTaskLists(model, member);
		model.addAttribute(member);
		return "member/show";
	}

	@RequestMapping(value = "/list", method = RequestMethod.GET)
	public String memberList(Model model){
		model.addAttribute("members", memberRepository.findAll());
		return "member/list";
	}

}

src/main/webapp/WEB-INF/views/member/list.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="sf" %>
<%@ taglib uri="http://www.springframework.org/security/tags" prefix="sec" %>
<div class="well">
	<h1 class="text-center"> Member list </h1>
	<div class="row" style="margin-top: 2em;">
		<div class="col-sm-12">
			<table class="table table-hover">
				<thead>
					<tr>
						<th>
							Name
						</th>
						<th>
							E-mail
						</th>
						<th>
							Active tasks
						</th>
					</tr>
				</thead>
				<tbody>
					<c:forEach items="${members}" var="member">
						<tr>
							<td>
								<a href="<c:url value="/member/show/${member.id}"/>">
									<c:out value="${member.fullName}"/>
								</a>
							</td>
							<td>
								<c:out value="${member.email}"/>
							</td>
							<td>
								${member.numberOfActiveTasks}
							</td>
						</tr>
					</c:forEach>
				</tbody>
			</table>
		</div>
	</div>
</div>

src/main/webapp/WEB-INF/views/member/register.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="sf" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring" %>
	<div class="well">
		<div class="row">
			<div class="col-md-4 col-sm-3"></div>
			<div class="col-md-4 col-sm-6">
				<h1 class="text-center">Register</h1>
				<sf:form method="POST" commandName="newMember">
					<div style="margin-bottom:0.5em; margin-top:1em;">
						<div class="text-danger" >
							${passwordsMatch ? "" : "Passwords don't match"}
						</div>
						<sf:errors path="*" element="div" cssClass="text-danger"/>
					</div>
					<spring:bind path="firstName">
						<div class="form-group ${status.error ? 'has-error' : ''}">
							<sf:label path="firstName">First name:</sf:label>
							<sf:input path="firstName" class="form-control  "/>
						</div>
					</spring:bind>

					<spring:bind path="surname">
						<div class="form-group ${status.error ? 'has-error' : ''}">
							<sf:label path="surname">Surname:</sf:label>
							<sf:input path="surname" class="form-control has-error"/>
						</div>
					</spring:bind>

					<spring:bind path="email">
						<div class="form-group ${status.error ? 'has-error' : ''}">
							<sf:label path="email">E-mail:</sf:label>
							<sf:input path="email" type="email" class="form-control"/>
						</div>
					</spring:bind>

					<%--
							regular html input is used for password, it will
							be saved as model attribute to be compared with the retyped password
					--%>
					<spring:bind path="password">
						<div class="form-group ${status.error ? 'has-error' : ''}">
							<sf:label path="password">Password:</sf:label>
							<sf:password path="password" class="form-control"/>
						</div>
					</spring:bind>
					<div class="form-group ${passwordsMatch ? '' : 'has-error'}">
						<label id="inputRetypePassword">Retype password:</label>
						<input id="inputRetypePassword" type="password" name="retypedPassword" class="form-control"/>
					</div>
					<input type="submit" value="Register" class="btn btn-primary"/>
				</sf:form>
			</div>
			<div class="col-md-4 col-sm-3"></div>
		</div>
	</div>

src/main/webapp/WEB-INF/views/member/show.jsp
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="sf" %>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %>

	<div class="well">
		<div class="row">
			<div class="col-sm-3">
				<h1><c:out value="${member.fullName}"/></h1>
				<c:forEach items="${member.authorities}" var="auth">
					<div>
						<label class="label label-info">
							${auth.friendlyName}
						</label>
					</div>
				</c:forEach>
				<div style="margin-top: 2em;">
					<c:out value="${member.email}"/>
				</div>
			</div>
			<div class="col-sm-9">
				<div class="row">
					<div class="col-sm-8 col-xs-10">
						<c:choose>
							<c:when test="${member.assignedTasks.size()==0 && member.managedProjects.size()==0}">
								<h3>No tasks have been assigned to this member yet</h3>
							</c:when>
							<c:otherwise>
								<h2> Tasks: </h2>
								<tiles:insertAttribute name="tasks"/>
							</c:otherwise>
						</c:choose>

						<c:if test="${member.managedProjects.size() > 0}">
							<h2 style="margin-top:2em;"> Managed Projects: </h2>
							<div class="panel panel-default">
								<div class="panel-body">
									<table class="table table-hover">
										<thead>
											<tr>
												<th>Name</th>
												<th>Number of tasks</th>
											</tr>
										</thead>
										<tbody>
											<c:forEach items="${member.managedProjects}" var="project">
												<tr>
													<td>
														<a href="<c:url value="/project/show/${project.id}"/>"><c:out value="${project.name}"/></a>
													</td>
													<td>
														${project.tasks.size()}
													</td>
												</tr>
											</c:forEach>
										</tbody>
									</table>
								</div>
							</div>
						</c:if>
					</div>
					<div class="col-sm-4 col-cs-2"></div>
				</div>
			</div>
		</div>
	</div>